[core]
cache_dir = ~/.cache/mopidy
config_dir = ~/.config/mopidy
data_dir = ~/.local/share/mopidy

[audio]
output = autoaudiosink

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
default_app = iris

[file]
enabled = true
media_dirs = /mnt/nas/media/music_clean|Music

[local]
enabled = true
media_dir = /mnt/nas/media/music_clean

[iris]
enabled = true

[mpd]
enabled = true
hostname = 127.0.0.1
